### ISSUE TITLE
Azure Web Apps?

### ISSUE THREAD

**Issue by oviliz** [credativ/icingaweb2-module-azure#6]
Hi guys, is there a way to monitor App Services or collect metrics from Application Insights?

**Comment by archandha** [comment]
Hi there,
I would assume, there is a way to import these. The Icinga Director plugin is more about importing objects to be monitored from Azure into Icinga2, not directly monitoring them. Currently, the importer does not include app services and the development came to a halt for now due to lack of need.

If you need extensions on this, feel free to submit pull requests. You might as well talk to our sales dept.
